# Setup
title: Gaby Méndez
tagline: Designer Turned Developer
url: https://gabichuelas.com
# paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# pages in nav bar
include: ['_pages']

# pages across header
pages_list:
  about: '/blog'
  archive: '/archive'


# Specify the author for blog posts
author:
  name: Gaby Mendez
  url: http://github.com/gabichuelas
  email: gmendez90@gmail.com

# Custom vars
version: 3.0.0

# Custom additions
excerpt_separator: <!--more-->
